// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriGuide.Models;

#nullable disable

namespace NutriGuide.Migrations
{
    [DbContext(typeof(NutriGuideDbContext))]
    [Migration("20241117102217_Bmi")]
    partial class Bmi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriGuide.Models.Bmi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tuổi của trẻ");

                    b.Property<float>("FenaleBmi")
                        .HasColumnType("real")
                        .HasColumnName("BMI TB của bé gái");

                    b.Property<float>("MaleBmi")
                        .HasColumnType("real")
                        .HasColumnName("BMI TB của bé trai");

                    b.HasKey("Id");

                    b.ToTable("Bmis");
                });
#pragma warning restore 612, 618
        }
    }
}
